### PR TITLE
Fix stg schema

### LINKED ISSUE #98: chore: Update model `yml` column definitions / metadata
The model metadata outlined in various `yml` files throughout the project are out of date. 

For example it would appear that the medications staging file only has datetime columns: https://github.com/OHDSI/dbt-synthea/blob/1c148f27f223bfbb008720ff5cb41bbfee71e24e/models/staging/synthea/_synthea__models.yml#L559-L565

However, there are more columns which are not referenced:

https://github.com/OHDSI/dbt-synthea/blob/1c148f27f223bfbb008720ff5cb41bbfee71e24e/models/staging/synthea/stg_synthea__medications.sql#L15-L31

This can / will cause problems in the future, and should be updated to properly reflect what we expect in each model.

### PR DESCRIPTION
**Pull request by katy-sadowski**
Add columns added to stg models.  Fixes #98

### CODE REVIEW

**Comment by lawrenceadams** [comment]
Solid stuff @katy-sadowski !

I think the following is still a bit off though (spelling mistake and datetime rather than date)? Then I think it is good to go!

https://github.com/OHDSI/dbt-synthea/blob/543738cecc9e78d3f715ca860240f8bea494f396/models/staging/synthea/_synthea__models.yml#L336-L341

**Review by lawrenceadams — CHANGES_REQUESTED** [review]
as per comment above

**Comment by katy-sadowski** [comment]
whoops! fixed!

**Review by lawrenceadams — APPROVED** [review]
Lovely! Nice one!

**Pull request merged**
