### PR TITLE
Clarified about where to create `.dbt` Folder

### PR DESCRIPTION
**Pull request by TheCedarPrince**
Added some notes about where to create the `.dbt` folder. Didn't know the proper solution for Windows off the top of my noggin however. Also, does the `.dbt` folder have to live at root?

### CODE REVIEW

**Review by katy-sadowski — DISMISSED** [review]
Thanks for this!

**Comment by katy-sadowski** [comment]
Regarding location of .dbt, it does not have to be at root. Maybe we could link out to this page for more info? https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles

**Comment by lawrenceadams** [comment]
> Regarding location of .dbt, it does not have to be at root. Maybe we could link out to this page for more info? https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles

I agree, I tend to leave the `profiles.yml` file in the root of the working directory - especially when using duckdb and not having a risk of leaking credentials -rather than at my `$HOME/.dbt`, and the [docs hint to this](https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles#:~:text=dbt%20will%20search%20the%20current%20working%20directory%20for%20the%20profiles.yml%20file%20and%20will%20default%20to%20the%20~/.dbt/%20directory%20if%20not%20found.)

> dbt will search the current working directory for the profiles.yml file and will default to the ~/.dbt/ directory if not found.

In fairness, this is unclear for a complete newcomer to dbt/dbt-synthea so I think is a good thing to add in

**Comment by TheCedarPrince** [comment]
Sure! I'll tweak the PR later today -- but what is the command to jump to root on Windows? `dir ... somthing` ?

**Comment by lawrenceadams** [comment]
Good question - I think it is `cd %HOMEPATH%` - but refuse to do any development work on Windows without using WSL so I have no idea 😆

**Comment by TheCedarPrince** [comment]
@lawrenceadams and @katy-sadowski , fixed up the language here.

**Review by katy-sadowski — COMMENTED** [review]
i think we should actually be more explicit about the options (or, just link out to the dbt docs for this): https://docs.getdbt.com/docs/core/connect-data-platform/connection-profiles#advanced-customizing-a-profile-directory

and either way, let's add `.dbt` and `profiles.yml` to .gitignore?

**Comment by katy-sadowski** [comment]
I fixed this in #109

**Pull request closed without merging**
