### PR TITLE
Remove OMOP seeds, rename vocab seeds

### PR DESCRIPTION
**Pull request by katy-sadowski**
It turns out the reason docs weren't rendering for some of the models was because there were seed files in the project with the same names as these models.  To fix that, I:

- Removed the empty table seeds and replaced them with SQL queries (which I prefer to the seeds anyways)
- Renamed the vocab seeds to have `_seed` postfix

The docs now fully populate for these models :)

### CODE REVIEW

**Review by lawrenceadams — APPROVED** [review]
Nice one! I think this is a better approach than empty seed files!

**Review by lawrenceadams — CHANGES_REQUESTED** [review]
oops - realised there's a bug! (not with the changes but with the side effects as a result of removing the seeds files)

**Review by lawrenceadams — APPROVED** [review]

**Comment by lawrenceadams** [comment]
I think this works well now!

**Comment by katy-sadowski** [comment]
Whoops!  It's weird I didn't get that error - maybe because those tables still existed in my schema from previous runs?  Agree with the change; thanks for catching that!  I'll merge in.

**Pull request merged**
